services:
  - type: web
    name: anget-bot
    env: python
    region: singapore
    plan: free
    branch: main
    autoDeploy: yes
    buildCommand: pip install -r requirements.txt
    startCommand: LONGPOLL=1 python tg_bot.py
    envVars:
      - key: TG_TOKEN
        value: 8830172184:AAGrwoeS4OU9lhLzcqTqkG8ipDSfFOfZuwg
